/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author crisc
 */
public class Battle extends javax.swing.JFrame {

    /**
     * Creates new form Battle
     */
    FondoPanel fondo = new FondoPanel();
    public Battle() {

        initComponents();
        cargarImagenPokemon();
        cargarImagenPokemon2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new FondoPanel();
        imageUrl = new javax.swing.JLabel();
        pokemon2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ataque1 = new javax.swing.JToggleButton();
        ataque2 = new javax.swing.JToggleButton();
        ataque3 = new javax.swing.JToggleButton();
        ataque4 = new javax.swing.JToggleButton();
        pokemon = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        entrenador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(132, 224, 223));

        imageUrl.setText("jLabel2");

        pokemon2.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(imageUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(pokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(133, Short.MAX_VALUE)
                                .addComponent(imageUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(pokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(132, 224, 223));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        ataque1.setBackground(new java.awt.Color(255, 255, 255));
        ataque1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ataque1.setText("jToggleButton1");
        ataque1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ataque1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ataque1MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 28, 0);
        jPanel3.add(ataque1, gridBagConstraints);

        ataque2.setBackground(new java.awt.Color(255, 255, 255));
        ataque2.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ataque2.setText("jToggleButton2");
        ataque2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ataque2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ataque2MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 28, 0);
        jPanel3.add(ataque2, gridBagConstraints);

        ataque3.setBackground(new java.awt.Color(255, 255, 255));
        ataque3.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ataque3.setText("jToggleButton3");
        ataque3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ataque3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ataque3MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 37, 28, 0);
        jPanel3.add(ataque3, gridBagConstraints);

        ataque4.setBackground(new java.awt.Color(255, 255, 255));
        ataque4.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ataque4.setText("jToggleButton4");
        ataque4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ataque4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ataque4MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 37, 28, 2);
        jPanel3.add(ataque4, gridBagConstraints);

        pokemon.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N
        pokemon.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 19, 0, 0);
        jPanel3.add(pokemon, gridBagConstraints);

        vida.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N
        vida.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel3.add(vida, gridBagConstraints);

        entrenador.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 12)); // NOI18N
        entrenador.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 19, 0, 0);
        jPanel3.add(entrenador, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void ataque4MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque4.setBackground(Color.white);
    }

    private void ataque4MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque4.setBackground(new Color (7, 155, 219));
    }

    private void ataque3MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque3.setBackground(Color.white);
    }

    private void ataque3MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque3.setBackground(new Color (7, 155, 219));
    }

    private void ataque2MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque2.setBackground(Color.white);
    }

    private void ataque2MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque2.setBackground(new Color (7, 155, 219));
    }

    private void ataque1MouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque1.setBackground(Color.white);
    }

    private void ataque1MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ataque1.setBackground(new Color (7, 155, 219));
    }



    private void cargarImagenPokemon() {
        new SwingWorker<ImageIcon, Void>() {
            @Override
            protected ImageIcon doInBackground() throws Exception {
                String urlImagen = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png"; // Pikachu
                Image imagen = ImageIO.read(new URL(urlImagen));
                return new ImageIcon(imagen);
            }

            @Override
            protected void done() {
                try {
                    ImageIcon icon = get();
                    // Escalar al tamaño del JLabel
                    Image imagenEscalada = icon.getImage().getScaledInstance(
                            imageUrl.getWidth(),
                            imageUrl.getHeight(),
                            Image.SCALE_SMOOTH);
                    imageUrl.setIcon(new ImageIcon(imagenEscalada));
                    imageUrl.setText("");
                } catch (Exception e) {
                    imageUrl.setText("Error al cargar");
                    e.printStackTrace();
                }
            }
        }.execute();
    }
    private void cargarImagenPokemon2() {
        new SwingWorker<ImageIcon, Void>() {
            @Override
            protected ImageIcon doInBackground() throws Exception {
                String urlImagen = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png"; // Charizard
                Image imagen = ImageIO.read(new URL(urlImagen));
                return new ImageIcon(imagen);
            }

            @Override
            protected void done() {
                try {
                    ImageIcon icon = get();
                    Image imagenEscalada = icon.getImage().getScaledInstance(
                            pokemon2.getWidth() > 0 ? pokemon2.getWidth() : 80,
                            pokemon2.getHeight() > 0 ? pokemon2.getHeight() : 80,
                            Image.SCALE_SMOOTH);
                    pokemon2.setIcon(new ImageIcon(imagenEscalada));
                    pokemon2.setText("");
                } catch (Exception e) {
                    pokemon2.setText("Error al cargar");
                    e.printStackTrace();
                }
            }
        }.execute();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JToggleButton ataque1;
    private javax.swing.JToggleButton ataque2;
    private javax.swing.JToggleButton ataque3;
    private javax.swing.JToggleButton ataque4;
    private javax.swing.JLabel entrenador;
    private javax.swing.JLabel imageUrl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pokemon;
    private javax.swing.JLabel pokemon2;
    private javax.swing.JLabel vida;
    // End of variables declaration

    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0 , getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
