/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Entrenador.Trainer;
import Pokemon.Pokemon;

import javax.swing.*;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author crisc
 */
public class pokemones extends javax.swing.JFrame {

    private  Trainer[] trainers;
    String[] pokemonsBattle = new String[2];


    /**
     * Creates new form pokemones
     */
    public pokemones() {
        initComponents();
    }
    public pokemones(Trainer[] trainers) {
        this.trainers = trainers;
        initComponents();
        // Puedes usar los trainers
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        batalla = new javax.swing.JButton();
        textoEscoger1 = new javax.swing.JTextField();
        escoger1 = new javax.swing.JLabel();
        textoEscoger2 = new javax.swing.JTextField();
        escoger2 = new javax.swing.JLabel();
        entrenador1 = new javax.swing.JLabel();
        entrenador2 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);


        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("equipo a2.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {trainers[0].getPokemonTeam().get(0).getPokedexId() ,trainers[0].getPokemonTeam().get(0).getName(), trainers[0].getPokemonTeam().get(0).getType(), trainers[0].getPokemonTeam().get(0).getHp()},
                        {trainers[0].getPokemonTeam().get(1).getPokedexId() ,trainers[0].getPokemonTeam().get(1).getName(), trainers[0].getPokemonTeam().get(1).getType(), trainers[0].getPokemonTeam().get(1).getHp()},
                        {trainers[0].getPokemonTeam().get(2).getPokedexId() ,trainers[0].getPokemonTeam().get(2).getName(), trainers[0].getPokemonTeam().get(2).getType(), trainers[0].getPokemonTeam().get(2).getHp()}
                },
                new String [] {
                        "ID", "Pokemon", "Elemento", "vida"
                }
        ){public boolean isCellEditable(int row, int column) {
            return false;
        }});
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("equipo b2.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {trainers[1].getPokemonTeam().get(0).getPokedexId() ,trainers[1].getPokemonTeam().get(0).getName(), trainers[1].getPokemonTeam().get(0).getType(), trainers[1].getPokemonTeam().get(0).getHp()},
                        {trainers[1].getPokemonTeam().get(1).getPokedexId() ,trainers[1].getPokemonTeam().get(1).getName(), trainers[1].getPokemonTeam().get(1).getType(), trainers[1].getPokemonTeam().get(1).getHp()},
                        {trainers[1].getPokemonTeam().get(2).getPokedexId() ,trainers[1].getPokemonTeam().get(2).getName(), trainers[1].getPokemonTeam().get(2).getType(), trainers[1].getPokemonTeam().get(2).getHp()}
                },
                new String [] {
                        "ID", "Pokemon", "Elemento", "vida"
                }
        ){public boolean isCellEditable(int row, int column) {
            return false;
        }});
        jScrollPane3.setViewportView(jTable2);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        batalla.setBackground(new java.awt.Color(255, 255, 255));
        batalla.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        batalla.setForeground(new java.awt.Color(0, 0, 0));
        batalla.setText("BATALLA");
        batalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                batallaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                batallaMouseExited(evt);
            }
        });
        batalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(batalla)
                                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(batalla)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoEscoger1.setText("");
        textoEscoger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEscoger1ActionPerformed(evt);
            }
        });

        escoger1.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        escoger1.setText("Elegir el primer pokemone:");

        textoEscoger2.setText("");
        textoEscoger2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEscoger2ActionPerformed(evt);
            }
        });

        escoger2.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        escoger2.setText("Elegir el primer pokemone:");

        entrenador1.setFont(new java.awt.Font("Roboto Condensed", 3, 12)); // NOI18N
        entrenador1.setText("Entrenador: " + trainers[0].getName());

        entrenador2.setFont(new java.awt.Font("Roboto Condensed", 3, 12)); // NOI18N
        entrenador2.setText("Entrenador: " + trainers[1].getName());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                                .addComponent(escoger2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(textoEscoger2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(155, 155, 155))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(163, 163, 163)
                                                                .addComponent(entrenador1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(166, 166, 166)
                                                                .addComponent(entrenador2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(62, 62, 62)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(61, 61, 61)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(escoger1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(textoEscoger1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(entrenador1)
                                                .addGap(15, 15, 15)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(escoger1)
                                                        .addComponent(textoEscoger1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(entrenador2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(textoEscoger2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(escoger2))
                                                .addGap(30, 30, 30))))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void batallaMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        batalla.setBackground(new Color(173, 216, 230));

    }

    @SuppressWarnings("empty-statement")
    private void batallaMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        batalla.setBackground(Color.white);
    }
    String pokemon1 , pokemon2;
    private void textoEscoger1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void textoEscoger2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void batallaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String pokemon1 = textoEscoger1.getText().trim();
        pokemonsBattle[0] = pokemon1;
        String pokemon2 = textoEscoger2.getText().trim();
        pokemonsBattle[1] = pokemon2;
        if(pokemon1.equals("") && pokemon2.equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un pokemon");
        } else if (!(trainers[0].getPokemonTeam().get(0).getPokedexId().equals(pokemon1) ||trainers[0].getPokemonTeam().get(1).getPokedexId().equals(pokemon1) || trainers[0].getPokemonTeam().get(2).getPokedexId().equals(pokemon1))) {
            JOptionPane.showMessageDialog(null, "esta mal el id del pokemon 1");
        }else if(!(trainers[1].getPokemonTeam().get(0).getPokedexId().equals(pokemon2) ||trainers[1].getPokemonTeam().get(1).getPokedexId().equals(pokemon2) || trainers[1].getPokemonTeam().get(2).getPokedexId().equals(pokemon2))){
            JOptionPane.showMessageDialog(null, "esta mal el id del pokemon 2");
        }else {
            System.out.println( pokemonsBattle[0] + pokemonsBattle[1]);
            this.dispose();
            Battle batallas = new Battle(trainers, pokemonsBattle);
            batallas.setVisible(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pokemones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pokemones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pokemones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pokemones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pokemones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton batalla;
    private javax.swing.JLabel entrenador1;
    private javax.swing.JLabel entrenador2;
    private javax.swing.JLabel escoger1;
    private javax.swing.JLabel escoger2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField textoEscoger1;
    private javax.swing.JTextField textoEscoger2;
    // End of variables declaration
}
